# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        cache: maven
    - name: Cache Maven packages
      uses: actions/cache@v4
        with:
          path: ~/.m2/repository # The path to cache the local repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }} # Cache key based on OS and pom.xml hash
        restore-keys: |
          ${{ runner.os }}-maven- # Fallback key if an exact match isn't found
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Generate coverage report using jacoco
      run: mvn -B jacoco:report
    - name: Upload coverage report to CodeCov
      run: bash <(curl -s https://codecov.io/bash)
    - name: Test checks publishing to github
      run: mvn -X com.j256.testcheckpublisher:test-check-publisher-maven-plugin:publish
